import { createSlice } from "@reduxjs/toolkit";

// createSlice is a function that accepts an initial state, an object of reducer functions, and a slice name, and automatically generates action creators and action types that correspond to the reducers and state.
const userSlice = createSlice({ // createSlice is a function that creates a slice of the Redux store
    name: "user",               // The slice name is used to identify the slice in the Redux store and is typically a lowercase string that describes the slice's purpose.
    initialState: {             // The initial state of the slice, which is an object that contains the initial values for the slice's state properties.
        username: "suprith",
        userInfo: null,
        ismenuToggle: false,
        iswatchPage: false,
        toggleloginIn: false,
    },
    reducers: {                // The reducers object contains the reducer functions that will handle actions dispatched to the slice. Each reducer function takes the current state and an action as arguments and returns a new state.
        addUser: (state, action) => { // The addUser reducer function updates the username property of the state with the payload of the dispatched action.
            state.username = action.payload;
        },
        userInfo: (state, action) => {
            state.userInfo = action.payload;
        },
        menuToggle: (state, action) => {
            state.ismenuToggle = !state.ismenuToggle;
        },
        hideMenu: (state, action) => {
            state.ismenuToggle = action.payload;
        },
        watchPage: (state, action) => {
            state.iswatchPage = action.payload;
        },
        toggleSignInnn: (state, action) => {
            state.toggleloginIn = !state.toggleloginIn;
        },
    }
})
export default userSlice.reducer; // Export the reducer function as the default export of the module. This allows the reducer to be imported and used in the Redux store configuration.
export const { addUser, menuToggle, watchPage, hideMenu, userInfo, toggleSignInnn } = userSlice.actions; // Export the action creators generated by createSlice. These action creators can be dispatched to update the state of the slice in the Redux store.
export const selectUser = (state) => state.user; // Export a selector function that retrieves the user slice of the state from the Redux store. This allows components to access the user slice of the state using this selector.
export const selectUserInfo = (state) => state.user.userInfo; // Export a selector function that retrieves the userInfo property of the user slice from the Redux store. This allows components to access the userInfo property of the user slice of the state using this selector.